digital_events_repository/src/java/digitalevents/grafico/controller/GrafricoEventosController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package digitalevents.grafico.controller;

import com.google.gson.Gson;
import edu.digitalEvents.modelo.dao.IEventoDAO;
import edu.digitalEvents.modelo.entities.GrafricoEventosView;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.faces.view.ViewScoped;
import edu.digitalEvents.modelo.entities.EntityGrafricoGlobal;

/**
 *
 * @author Juan
 */
@Named(value = "grafricoEventosController")
@ViewScoped
public class GrafricoEventosController implements Serializable{
    
    /**
     * Creates a new instance of GraficoEventosController
     */
    @EJB
    private IEventoDAO eDao;
    private List<EntityGrafricoGlobal> datosGrafricoEmpresarial;
    private List<EntityGrafricoGlobal> datosGrafricoInfantil;
    private List<EntityGrafricoGlobal> datosGrafricoFiestaTematica;

    @PostConstruct
    public void init() {

    }

    public List<EntityGrafricoGlobal> getDatosGrafricoEmpresarial() {
        datosGrafricoEmpresarial =new ArrayList<>();
        int contador = 1;
        String mesUsuario = null;
        for (GrafricoEventosView e : eDao.findAllEventosGrafricoEMPRESARIAL()) {
            switch (e.getMeses()) {
                case "January":
                    mesUsuario = "Enero";
                    break;
                case "February":
                    mesUsuario = "Febrero";
                    break;
                case "March":
                    mesUsuario = "Marzo";
                    break;
                case "April":
                    mesUsuario = "Abril";
                    break;
                case "May":
                    mesUsuario = "Mayo";
                    break;
                case "June":
                    mesUsuario = "Junio";
                    break;
                case "July":
                    mesUsuario = "Julio";
                    break;
                case "August":
                    mesUsuario = "Agosto";
                    break;
                case "September":
                    mesUsuario = "Septiembre";
                    break;
                case "October":
                    mesUsuario = "Octubre";
                    break;
                case "November":
                    mesUsuario = "Noviembre";
                    break;
                case "December":
                    mesUsuario = "Diciembre";
                    break;
                default:
                    throw new AssertionError();
            }
            EntityGrafricoGlobal cuen = new EntityGrafricoGlobal(contador++, e.getCuentaEventos(), e.getTipoevento(), mesUsuario);
            datosGrafricoEmpresarial.add(cuen);
        }
        return datosGrafricoEmpresarial;
    }

    public List<EntityGrafricoGlobal> getDatosGrafricoInfantil() {
        datosGrafricoInfantil =new ArrayList<>();
        int contador = eDao.findAllEventosGrafricoEMPRESARIAL().size()+1;
        String mesUsuario = null;
        for (GrafricoEventosView e : eDao.findAllEventosGrafricoINFANTILES()) {
            switch (e.getMeses()) {
                case "January":
                    mesUsuario = "Enero";
                    break;
                case "February":
                    mesUsuario = "Febrero";
                    break;
                case "March":
                    mesUsuario = "Marzo";
                    break;
                case "April":
                    mesUsuario = "Abril";
                    break;
                case "May":
                    mesUsuario = "Mayo";
                    break;
                case "June":
                    mesUsuario = "Junio";
                    break;
                case "July":
                    mesUsuario = "Julio";
                    break;
                case "August":
                    mesUsuario = "Agosto";
                    break;
                case "September":
                    mesUsuario = "Septiembre";
                    break;
                case "October":
                    mesUsuario = "Octubre";
                    break;
                case "November":
                    mesUsuario = "Noviembre";
                    break;
                case "December":
                    mesUsuario = "Diciembre";
                    break;
                default:
                    throw new AssertionError();
            }
            EntityGrafricoGlobal cuen = new EntityGrafricoGlobal(contador++, e.getCuentaEventos(), e.getTipoevento(), mesUsuario);
            datosGrafricoInfantil.add(cuen);
        }
        return datosGrafricoInfantil;
    }

    public List<EntityGrafricoGlobal> getDatosGrafricoFiestaTematica() {
        datosGrafricoFiestaTematica =new ArrayList<>();
        int contador = eDao.findAllEventosGrafricoINFANTILES().size()+eDao.findAllEventosGrafricoEMPRESARIAL().size()+1;
        String mesUsuario = null;
        for (GrafricoEventosView e : eDao.findAllEventosGrafrico()) {
            switch (e.getMeses()) {
                case "January":
                    mesUsuario = "Enero";
                    break;
                case "February":
                    mesUsuario = "Febrero";
                    break;
                case "March":
                    mesUsuario = "Marzo";
                    break;
                case "April":
                    mesUsuario = "Abril";
                    break;
                case "May":
                    mesUsuario = "Mayo";
                    break;
                case "June":
                    mesUsuario = "Junio";
                    break;
                case "July":
                    mesUsuario = "Julio";
                    break;
                case "August":
                    mesUsuario = "Agosto";
                    break;
                case "September":
                    mesUsuario = "Septiembre";
                    break;
                case "October":
                    mesUsuario = "Octubre";
                    break;
                case "November":
                    mesUsuario = "Noviembre";
                    break;
                case "December":
                    mesUsuario = "Diciembre";
                    break;
                default:
                    throw new AssertionError();
            }
            EntityGrafricoGlobal cuen = new EntityGrafricoGlobal(contador++, e.getCuentaEventos(), e.getTipoevento(), mesUsuario);
            datosGrafricoFiestaTematica.add(cuen);
        }

        return datosGrafricoFiestaTematica;
    }
     public String getDatosJsonEmpresarial() {
        Gson gson = new Gson();
        return gson.toJson(getDatosGrafricoEmpresarial());
    }
     public String getDatosJsonInfantil() {
        Gson gson = new Gson();
        return gson.toJson(getDatosGrafricoInfantil());
    }
     public String getDatosJsonTematica() {
        Gson gson = new Gson();
        return gson.toJson(getDatosGrafricoFiestaTematica());
    }
}

digital_events_repository/src/java/digitalevents/ventas/controller/EventoController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package digitalevents.ventas.controller;

import digitalevents.login.controllers.SessionController;
import edu.digitalEvents.modelo.dao.IEventoDAO;
import edu.digitalEvents.modelo.dao.IEventoReservadoViewDAO;
import edu.digitalEvents.modelo.dao.ISolicitudDAO;
import edu.digitalEvents.modelo.dao.jpa.EventoDAO;
import edu.digitalEvents.modelo.entities.EventoReservadoView;
import edu.digitalEvents.modelo.entities.EventosRealizadosView;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.io.Serializable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.servlet.http.HttpServletResponse;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;

/**
 *
 * @author Nicolas PC
 */
@Named(value = "eventoController")
@ViewScoped
public class EventoController implements Serializable {

    @Inject
    private SessionController se;
    @EJB
    private IEventoReservadoViewDAO eDAO;
    @EJB
    private IEventoDAO eRealizadosDao;
    private List<EventoReservadoView> eventosList;
    private List<EventosRealizadosView> eventosRealizadosList;
    private List<EventosRealizadosView> eventosRealizadosAlClienteList;

    /**
     * Creates a new instance of EventoController
     */
    public EventoController() {
    }

    @PostConstruct
    public void init() {
    }

    public List<EventoReservadoView> getEventosList() {
        if (eventosList == null || eventosList.isEmpty()) {
            eventosList = eDAO.findAll();
        }
        return eventosList;
    }

    public List<EventosRealizadosView> getEventosRealizadosList() {
        if (eventosRealizadosList == null || eventosRealizadosList.isEmpty()) {
            eventosRealizadosList = eRealizadosDao.findAllEventsoRealizados();
        }
        return eventosRealizadosList;
    }

    public List<EventosRealizadosView> getEventosRealizadosAlClienteList() {
        if (eventosRealizadosAlClienteList == null || eventosRealizadosAlClienteList.isEmpty()) {
            eventosRealizadosList = eRealizadosDao.findAllEventsoRealizadosAlCliente(se.getUser().getNombres());
        }
        return eventosRealizadosAlClienteList;
    }

    public void export() {
        try {
            System.out.println("VAMOS A IMPRIMIR EL REPORTE");
            FacesContext fc = FacesContext.getCurrentInstance();
            ExternalContext ec = fc.getExternalContext();
            File jasper = new File(ec.getRealPath("/WEB-INF/classes/reporteEventosRealizados/ReporteEventosRealizados.jasper"));
            //JRBeanCollectionDataSource jasperDS = new JRBeanCollectionDataSource(usuarioList);
            Map<String, Object> params = new HashMap<>();
            params.put("logosystem", ec.getRealPath("/resources/img/logo.png"));
            JasperPrint jp = JasperFillManager.fillReport(jasper.getPath(), params, new JRBeanCollectionDataSource(getEventosRealizadosList(), false));
            HttpServletResponse hsr = (HttpServletResponse) ec.getResponse();
            hsr.addHeader("Content-disposition", "attachment; filename=reporteInventario.pdf");
            OutputStream os = hsr.getOutputStream();
            JasperExportManager.exportReportToPdfStream(jp, os);
            os.flush();
            os.close();
            fc.responseComplete();
        } catch (JRException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }

    }

    public void exportCliente() {
        try {
            System.out.println("VAMOS A IMPRIMIR EL REPORTE");
            FacesContext fc = FacesContext.getCurrentInstance();
            ExternalContext ec = fc.getExternalContext();
            File jasper = new File(ec.getRealPath("/WEB-INF/classes/reporteEventosRealizados/ReporteEventosRealizados.jasper"));
            //JRBeanCollectionDataSource jasperDS = new JRBeanCollectionDataSource(usuarioList);
            Map<String, Object> params = new HashMap<>();
            params.put("logosystem", ec.getRealPath("/resources/img/logo.png"));
            JasperPrint jp = JasperFillManager.fillReport(jasper.getPath(), params, new JRBeanCollectionDataSource(getEventosRealizadosAlClienteList(), false));
            HttpServletResponse hsr = (HttpServletResponse) ec.getResponse();
            hsr.addHeader("Content-disposition", "attachment; filename=reporteInventario.pdf");
            OutputStream os = hsr.getOutputStream();
            JasperExportManager.exportReportToPdfStream(jp, os);
            os.flush();
            os.close();
            fc.responseComplete();
        } catch (JRException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }

    }

}

digital_events_repository/web/SI/recreador/eventos/eventos.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="/WEB-INF/includes/template/main.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:a="http://xmlns.jcp.org/jsf/passthrough"
                xmlns:p="http://primefaces.org/ui">
    <ui:define name="scripts-grafricos">    
        <script type="text/javascript">
            var chart;

            function updateDatos(cuentasCDT) {
                chart.options.data[0].dataPoints = cuentasCDT;
                chart.render();
            }
            function toggleDataSeries(e) {
                if (typeof (e.dataSeries.visible) === "undefined" || e.dataSeries.visible) {
                    e.dataSeries.visible = false;
                } else {
                    e.dataSeries.visible = true;
                }
                e.chart.render();
            }
            $(document).ready(function () {
                chart = new CanvasJS.Chart("myChartEventos", {
                    animationEnabled: true,
                    exportEnabled: true, 
                    toolTip: {
                        shared: true
                    },
                    legend: {
                        cursor: "pointer",
                        itemclick: toggleDataSeries
                    }});
                chart.options.axisY = {
                    suffix: "",
                    lineThickness: 2,
                    title: 'TIPOS EVENTOS',

                    scaleBreaks: {
                        type: "wavy",
                        customBreaks: [{
                                startValue: 3,
                                endValue: 4
                            },
                            {
                                startValue: 3,
                                endValue: 4
                            }
                        ]}

                };
                chart.options.title = {
                   
                };
                seriesEmpresarial = {
                    /*** Change type "column" to "bar", "area", "line" or "pie"***/
                    type: "column",
                    showInLegend: true,
                    name: "{label}",
                    indexLabel: "{labelDatos}",
                    isIntermediateSum: true
                };
                seriesTematico = {
                    /*** Change type "column" to "bar", "area", "line" or "pie"***/
                    type: "column",
                    showInLegend: true,
                    name: "{label}",
                    indexLabel: "{labelDatos}",
                    isIntermediateSum: true
                };
                 seriesFiestaInfantil = {
                    /*** Change type "column" to "bar", "area", "line" or "pie"***/
                    type: "column",
                    showInLegend: true,
                    name: "{label}",
                    indexLabel: "{labelDatos}",
                    isIntermediateSum: true
                };
                chart.options.data = [];
                chart.options.data.push(seriesEmpresarial);
                chart.options.data.push(seriesTematico);
                chart.options.data.push(seriesFiestaInfantil);
                seriesEmpresarial.dataPoints = #{grafricoEventosController.datosJsonEmpresarial};
                seriesTematico.dataPoints = #{grafricoEventosController.datosJsonTematica};
                seriesFiestaInfantil.dataPoints = #{grafricoEventosController.datosJsonInfantil};
                chart.render();
            });
            function convertCanvasToImage(canvas) {
                var $canvas = $("#container-canvas-1 canvas");
                var data = $canvas[0].toDataURL("image/jpg");
                console.log(data);
                alert(data);
                $("#imgPrb").attr("src", data);
                var image = new Image();
                image.src = data;
                document.body.appendChild(image);
            }
        </script>
    </ui:define>
    <ui:define name="content">
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <h:form>
                                <div class="card-header card-header-success colorc">
                                    <div class="row">
                                        <div class="col-9">
                                            <h4 class="card-title">Grafrico Eventos</h4>
                                            <p class="card-category">Aquí encontraras un reporte grafrico de los eventos sin importar el estado ordenados por meses</p>
                                        </div>
                                        
                                    </div>
                                </div>
                                <div class="card-body card-header card-chart card-header-success">
                                    <div class="ct-chart" id="myChartEventos" style="width: 100%; height: 300px;"></div>
                                </div>
                            </h:form>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <h:form>
                                <div class="card-header card-header-success colorc">
                                    <div class="row">
                                        <div class="col-9">
                                            <h4 class="card-title">Eventos Reservados</h4>
                                            <p class="card-category">Aquí encontraras los eventos aprobados</p>
                                        </div>
                                        <div class="col-3">
                                            <a class="btn btn-info" href="#{request.contextPath}/SI/administrador/ventas/registrar.xhtml">
                                                <i class="far fa-calendar-plus movericon"></i>
                                                <span>Añadir Solicitud</span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <div class="table-responsive">
                                        <h:form prependId="false">
                                            <h:dataTable class="table table-striped text-center" value="#{eventoController.eventosList}" var="s">
                                                <h:column><f:facet name="header">ID</f:facet>#{s.id}</h:column>
                                                <h:column><f:facet name="header">USUARIO</f:facet>#{s.usuario}</h:column>                                                
                                                <h:column><f:facet name="header">CONTACTO</f:facet>#{s.contacto}</h:column>                                                
                                                <h:column>
                                                    <f:facet name="header">FECHA RESERVA</f:facet>
                                                    <h:outputText value="#{s.fecha}">
                                                        <f:convertDateTime pattern="yyyy-MM-dd HH:mm"/>
                                                    </h:outputText>
                                                </h:column>                                                
                                                <h:column><f:facet name="header">DIRECCION</f:facet>#{s.direccion}</h:column>                                                
                                                <h:column><f:facet name="header">ESTADO</f:facet>#{s.estado}</h:column>                                                 
                                                <h:column><f:facet name="header">SALDO</f:facet>#{s.saldo}</h:column>                                                 
                                                <h:column><f:facet name="header">OPCIONES</f:facet>
                                                    <h:commandLink class="td-actions text-right btn btn-info" rel="tooltip" >
                                                        <f:ajax render=":modalVisualizarSolicitudContent"/>
                                                        <i class="material-icons">event</i>
                                                    </h:commandLink>                                                                                                       
                                                </h:column>                                                 
                                            </h:dataTable>
                                        </h:form>
                                    </div>
                                </div>
                            </h:form>
                        </div>
                    </div>
                </div>
            </div>
        </div>      
    </ui:define>
    <ui:define name="modals-page">

        

    </ui:define>
</ui:composition>