digital_events_repository/src/java/digitalevents/grafico/controller/GrafricoInventarioController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package digitalevents.grafico.controller;

import com.google.gson.Gson;
import edu.digitalEvents.modelo.dao.IMaterialDAO;
import edu.digitalEvents.modelo.entities.EntityGrafricoGlobal;
import edu.digitalEvents.modelo.entities.GrafricoInventarioView;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.faces.view.ViewScoped;

/**
 *
 * @author Juan
 */
@Named(value = "grafricoInventarioController")
@ViewScoped
public class GrafricoInventarioController implements Serializable {

    /**
     * Creates a new instance of GraficoInventarioController
     */
    @EJB
    private IMaterialDAO mDao;
    private List<EntityGrafricoGlobal> datosMaterialesBuenaCalidad;
    private List<EntityGrafricoGlobal> datosMaterialesMalaCalidad;

    @PostConstruct
    public void init() {

    }

    public List<EntityGrafricoGlobal> getDatosMaterialesBuenaCalidad() {
        datosMaterialesBuenaCalidad = new ArrayList<>();
        int contador = 1;
        for (GrafricoInventarioView e : mDao.findAllInventarioGrafrico()) {
            EntityGrafricoGlobal cuen = new EntityGrafricoGlobal(contador++, e.getCantidad(), e.getEstadoMaterial(), e.getTipoMaterial());
            datosMaterialesBuenaCalidad.add(cuen);
        }
        return datosMaterialesBuenaCalidad;
    }

    public List<EntityGrafricoGlobal> getDatosMaterialesMalaCalidad() {
        datosMaterialesMalaCalidad = new ArrayList<>();
        int contador = mDao.findAllInventarioGrafrico().size()+1;
        for (GrafricoInventarioView e : mDao.findAllInventarioMalEstadoGrafrico()) {
            EntityGrafricoGlobal cuen = new EntityGrafricoGlobal(contador++, e.getCantidad(), e.getEstadoMaterial(), e.getTipoMaterial());
            datosMaterialesMalaCalidad.add(cuen);
        }
        return datosMaterialesMalaCalidad;
    }

    public String getDatosJsonBuenaCalidad() {
        Gson gson = new Gson();
        return gson.toJson(getDatosMaterialesBuenaCalidad());
    }

    public String getDatosJsonMalaCalidad() {
        Gson gson = new Gson();
        return gson.toJson(getDatosMaterialesMalaCalidad());
    }
    
}

digital_events_repository/src/java/digitalevents/inventario/controller/CargaMasivaInventarioCSVController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package digitalevents.inventario.controller;

import digitalevents.utils.MensajesUtilCSV;
import digitalevents.utils.MessageUtil;
import edu.digitalEvents.modelo.dao.IMaterialDAO;
import edu.digitalEvents.modelo.entities.InventarioCSV;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.InputStream;
import java.io.Serializable;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.faces.view.ViewScoped;
import javax.servlet.http.Part;
import net.sf.jasperreports.engine.util.FileBufferedOutputStream;

/**
 *
 * @author Juan
 */
@Named(value = "cargaMasivaInventarioCSVController")
@ViewScoped
public class CargaMasivaInventarioCSVController implements Serializable{
    @EJB
    private IMaterialDAO mDao;
    private Part multiPartInventario;
    private InventarioCSV csvInventario;
    
    /**
     * Creates a new instance of CargaMasivaInventarioCSVController
     */
    public CargaMasivaInventarioCSVController() {
    }
    @PostConstruct
    public void init(){
        
    }

    public Part getMultiPartInventario() {
        return multiPartInventario;
    }

    public void setMultiPartInventario(Part multiPartInventario) {
        this.multiPartInventario = multiPartInventario;
    }

    public InventarioCSV getCsvInventario() {
        return csvInventario;
    }

    public void setCsvInventario(InventarioCSV csvInventario) {
        this.csvInventario = csvInventario;
    }
    public void fileUploadCsvInventario(){
        String rutas="";
        if(multiPartInventario!=null){
            File carpetaInventario = new File(FacesContext.getCurrentInstance().getExternalContext().getRealPath("") + "/CargaCSVInventario");
            if (!carpetaInventario.exists()) {
                carpetaInventario.mkdirs();
            }
            try(InputStream archivo = multiPartInventario.getInputStream()) {
                Files.copy(archivo, new File(carpetaInventario,multiPartInventario.getSubmittedFileName()).toPath(),StandardCopyOption.REPLACE_EXISTING);
                rutas=FacesContext.getCurrentInstance().getExternalContext().getRealPath("")+"/CargaCSVInventario/" + multiPartInventario.getSubmittedFileName();
                registrarInventarioCSV(rutas);
                MensajesUtilCSV.infoMensaje("", rutas, "");
            } catch (Exception e) {
                 e.printStackTrace();
            }
        }
        
        
    }
    public void registrarInventarioCSV(String ruta){
        String r=ruta;
        BufferedReader fr= null;
        try {
            MensajesUtilCSV.infoMensaje(null, "Carga de datos exitosa", "");
            fr=new BufferedReader(new FileReader(r));
            String linea=fr.readLine();
            while (linea!=null) {
                String[] array=linea.split(";");
                int id=mDao.count()+1;
                InventarioCSV inventario = new InventarioCSV(id, array[0], Integer.parseInt(array[1]), array[2], Integer.parseInt(array[3]), array[4]);
                mDao.cargaMasivaInventario(inventario);
                linea = fr.readLine();
                MessageUtil.addInfoMessage(null, "Carga de datos exitosa", "Los datos del usuario se han cargado correctamente,", false);
                 System.out.println("Carga de datos exitosa con los datos");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (fr != null) {
                try {
                    fr.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }

            }

        }
    }
    
}

digital_events_repository/src/java/digitalevents/inventario/controller/InventarioController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package digitalevents.inventario.controller;

import digitalevents.utils.MessageUtil;
import edu.digitalEvents.modelo.dao.IDisponibilidadMaterialDAO;
import edu.digitalEvents.modelo.dao.IMaterialDAO;
import edu.digitalEvents.modelo.entities.DisponilidadMaterial;
import edu.digitalEvents.modelo.entities.Material;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.Serializable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.event.PhaseId;
import javax.inject.Named;
import javax.faces.view.ViewScoped;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.Part;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import org.apache.poi.util.IOUtils;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.primefaces.model.UploadedFile;

/**
 *
 * @author Nicolas PC
 */
@Named(value = "inventarioController")
@ViewScoped
public class InventarioController implements Serializable {

    @EJB
    private IMaterialDAO mDAO;
    @EJB
    private IDisponibilidadMaterialDAO dmDAO;

    private Material nuevoMaterial;
    private Material materialSeleccionado;
    private Material current;
    private List<Material> materialList;

    private DisponilidadMaterial dispMaterial;
    private List<DisponilidadMaterial> estadoMaterialList;

    private UploadedFile file;
    private Part image;

    /**
     * Creates a new instance of inventarioController
     */
    public InventarioController() {
    }

    @PostConstruct
    public void init() {
    }

    public Material getNuevoMaterial() {
        if (nuevoMaterial == null) {
            nuevoMaterial = new Material();
        }
        return nuevoMaterial;
    }

    public Material getMaterialSeleccionado() {
        return materialSeleccionado;
    }

    public List<Material> getMaterialList() {
        if (materialList == null || materialList.isEmpty()) {
            materialList = mDAO.findAll();
            for (Material d : mDAO.findAll()) {
                System.out.println("Hola" + d.getEstado());
            }
        }
        return materialList;
    }

    public List<DisponilidadMaterial> getEstadoMaterialList() {
        if (estadoMaterialList == null || estadoMaterialList.isEmpty()) {
            estadoMaterialList = dmDAO.findAll();

        }
        return estadoMaterialList;
    }

    public UploadedFile getFile() {
        return file;
    }

    public void setFile(UploadedFile file) {
        this.file = file;
    }

    public Part getImage() {
        return image;
    }

    public void setImage(Part image) {
        this.image = image;
    }

    public void materialSeleccionado(Material m) {
        System.out.println("Se selecciono el articulo: ");
        System.out.println(m);
        materialSeleccionado = m;
    }

    public void actualizar() {
        try {
            mDAO.update(materialSeleccionado);
            MessageUtil.addInfoMessage(null, "Actualización exitosa", "Los datos del material se han actualizaco correctamente,", false);
        } catch (Exception e) {
            e.printStackTrace();
            MessageUtil.addErrorMessage(null, "Error al actualizar el material", e.getMessage(), false);
        }
    }

    public void registrar() {
        try {
            if (nuevoMaterial.getCantidad() > 0) {
                mDAO.register(nuevoMaterial);
                MessageUtil.addInfoMessage(null, "REGISTRO EXITOSO", "El material se inserto correctamente", false);

            } else {
                MessageUtil.addErrorMessage(null, "Error de validación", "Fallo algo al resgistrar", false);
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageUtil.addErrorMessage(null, "Error al registrar el material", e.getMessage(), false);
        }
    }

    public void eliminar() {
        try {
            mDAO.delete(materialSeleccionado);
            MessageUtil.addInfoMessage(null, "Eliminación exitosa", "Los datos del material se han eliminado correctamente,", false);
        } catch (Exception e) {
            e.printStackTrace();
            MessageUtil.addErrorMessage(null, "Error al eliminar el material", e.getMessage(), false);

        }
    }

    public void export() {
        try {
            System.out.println("VAMOS A IMPRIMIR EL REPORTE");
            FacesContext fc = FacesContext.getCurrentInstance();
            ExternalContext ec = fc.getExternalContext();
            File jasper = new File(ec.getRealPath("/WEB-INF/classes/reporteInventario/ReporteMateriales.jasper"));
            //JRBeanCollectionDataSource jasperDS = new JRBeanCollectionDataSource(usuarioList);
            Map<String, Object> params = new HashMap<>();
            params.put("logosystem", ec.getRealPath("/resources/img/logo.png"));
            params.put("grafricoimg", ec.getRealPath("/resources/img/ChartInventario.png"));
            JasperPrint jp = JasperFillManager.fillReport(jasper.getPath(), params, new JRBeanCollectionDataSource(getMaterialList(), false));
            HttpServletResponse hsr = (HttpServletResponse) ec.getResponse();
            hsr.addHeader("Content-disposition", "attachment; filename=reporteInventario.pdf");
            OutputStream os = hsr.getOutputStream();
            JasperExportManager.exportReportToPdfStream(jp, os);
            os.flush();
            os.close();
            fc.responseComplete();
        } catch (JRException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }

    }

    public void upload(FileUploadEvent event) {
        UploadedFile uploadedFile = event.getFile();
        String filename = uploadedFile.getFileName();
        String contentType = uploadedFile.getContentType();
        byte[] contents = uploadedFile.getContents();
    }

    public void doUpload() {
        try {
            InputStream in = image.getInputStream();
            File f = new File("/Users/Usuario/Desktop/CopiaProyecto/" + image.getSubmittedFileName());
            f.createNewFile();
            FileOutputStream out = new FileOutputStream(f);

            byte[] buffer = new byte[1024];
            int length;

            while ((length = in.read(buffer)) > 0) {
                out.write(buffer, 0, length);
            }

            out.close();
            in.close();

        } catch (Exception e) {
            e.printStackTrace(System.out);
        }
    }

    public void uploadFile() {
        if (file != null) {
            try {
                byte[] data = file.getContents();
                mDAO.udpateByImage(data, materialSeleccionado.getId());
                MessageUtil.addInfoMessage(null, "Actualización exitosa", "La imagen ha sido cargada correctamente", false);

            } catch (Exception e) {
                e.printStackTrace();
                MessageUtil.addInfoMessage(null, "ERROR", "INTENTALO DE NUEVO", false);
            }
        }
    }

    public StreamedContent imageStream() {
        try {
            FacesContext fc = FacesContext.getCurrentInstance();
            if (fc.getCurrentPhaseId() == PhaseId.RENDER_RESPONSE) {
                // Renderizamos el html retornando un espacio con el contenido de la imagen obteniendo el correcto URL.   
                return new DefaultStreamedContent();
            } else {
                // El navegador requiere la imagen. Retorna un StramedContent real con la imgen byte
                String imageId = fc.getExternalContext().getRequestParameterMap().get("imageId");
                Material image = mDAO.findByPK(Integer.valueOf(imageId));
                return new DefaultStreamedContent(new ByteArrayInputStream(image.getImage()));
            }
        } catch (NumberFormatException e) {
            e.printStackTrace();
        }
        return null;
    }
}

digital_events_repository/web/SI/recreador/inventario/inventario.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="/WEB-INF/includes/template/main.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:a="http://xmlns.jcp.org/jsf/passthrough"
                xmlns:p="http://primefaces.org/ui">
<ui:define name="scripts-grafricos">
        
         <script type="text/javascript">
            var chart;

            function updateDatos(cuentasCDT) {
                chart.options.data[0].dataPoints = cuentasCDT;
                chart.render();
            }
            function toggleDataSeries(e) {
                if (typeof (e.dataSeries.visible) === "undefined" || e.dataSeries.visible) {
                    e.dataSeries.visible = false;
                } else {
                    e.dataSeries.visible = true;
                }
                e.chart.render();
            }
            $(document).ready(function () {
                chart = new CanvasJS.Chart("myChartInventarios", {
                    animationEnabled: true,
                    exportEnabled: true, 
                    toolTip: {
                        shared: true
                    },
                    legend: {
                        cursor: "pointer",
                        itemclick: toggleDataSeries
                    }});
                chart.options.axisY = {
                    suffix: "",
                    lineThickness: 2,
                    title: 'TIPOS MATERIALES',

                    scaleBreaks: {
                        type: "wavy",
                        customBreaks: [{
                                startValue: 3,
                                endValue: 4
                            },
                            {
                                startValue: 3,
                                endValue: 4
                            }
                        ]}

                };
                chart.options.title = {
                   
                };
                seriesBuena = {
                    /*** Change type "column" to "bar", "area", "line" or "pie"***/
                    type: "line",
                    showInLegend: true,
                    name: "{label}",
                    indexLabel: "{labelDatos}",
                    isIntermediateSum: true
                };
                seriesMala = {
                    /*** Change type "column" to "bar", "area", "line" or "pie"***/
                    type: "column",
                    showInLegend: true,
                    name: "{label}",
                    indexLabel: "{labelDatos}",
                    isIntermediateSum: true
                };
                chart.options.data = [];
                chart.options.data.push(seriesBuena);
                chart.options.data.push(seriesMala);
                seriesBuena.dataPoints = #{grafricoInventarioController.datosJsonBuenaCalidad};
                seriesMala.dataPoints = #{grafricoInventarioController.datosJsonMalaCalidad};
                chart.render();
            });
            
        </script>
    </ui:define>
    <ui:define name="content">
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <h:form>
                                <div class="card-header card-header-success colorc">
                                    <div class="row">
                                        <div class="col-6">
                                            <h4 class="card-title">Grafrico Estadistico Inventario</h4>
                                            <p class="card-category">Aquí encontraras un grafrico estadistico en el cual se muestra la cantidad de materiales que se encuentran en buen estado.</p>
                                        </div>
                                        
                                    </div>
                                </div>
                                <div class="card-body card-header card-chart card-header-success">
                                   <div class="ct-chart" id="myChartInventarios" style="width: 100%; height: 300px;"></div>
                                </div>
                            </h:form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header card-header-success colorc">
                                <div class="row">
                                    <div class="col-9">
                                        <h4 class="card-title">Inventario</h4>
                                        <p class="card-category">Aquí encontraras los materiales que se encuentran en el almacen.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <h:form prependId="false">
                                        <h:dataTable class="table table-striped text-center" value="#{inventarioController.materialList}" var="m">
                                            <h:column><f:facet name="header">ID</f:facet>#{m.id}</h:column>
                                            <h:column><f:facet name="header">TIPO MATERIAL</f:facet>#{m.tipoMaterial}</h:column>                                                
                                            <h:column><f:facet name="header">CANTIDAD</f:facet>#{m.cantidad}</h:column>                                                
                                            <h:column><f:facet name="header">ESTADO</f:facet>#{m.estado}</h:column>                                                 
                                            <h:column><f:facet name="header">DISPONIBILIDAD</f:facet>#{m.disponilidad.estado}</h:column>                                                 
                                            <h:column><f:facet name="header">OPCIONES</f:facet>
                                                <h:commandLink class="td-actions text-right btn btn-success" actionListener="#{inventarioController.materialSeleccionado(m)}"
                                                               a:data-toggle="modal" a:data-target="#modalEditarMaterial" rel="tooltip" >
                                                    <f:ajax render=":modalEditarMaterialContent"/>
                                                    <i class="material-icons">edit</i>
                                                </h:commandLink> 
                                            </h:column>                                                 
                                        </h:dataTable>
                                    </h:form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </ui:define>
    <ui:define name="modals-page">

        <!--modal editar-->
        <div class="modal fade" id="modalEditarMaterial" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
                <h:form prependId="false">
                    <h:panelGroup id="modalEditarMaterialContent" class="modal-content" layout="block">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title titulom" id="exampleModalLabel">Actualizar Solicitud</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <h:form prependId="false">
                                    <div class="form-group row">
                                        <div class="col-3">
                                            <label class="control-label mb-1">ID Material:</label>
                                            <div class="form-control">#{inventarioController.materialSeleccionado.id}</div>
                                        </div>
                                        <div class="col-3">
                                            <label class="control-label mb-1">Tipo Material:</label>
                                            <h:inputText id="tipoMaterial" value="#{inventarioController.materialSeleccionado.tipoMaterial}"
                                                         class="form-control" a:type="text"/>
                                        </div>
                                        <div class="col-3">
                                            <label class="control-label mb-1">Cantidad:</label>
                                            <h:inputText id="cantidad" value="#{inventarioController.materialSeleccionado.cantidad}"
                                                         class="form-control" a:type="number" maxlength="100" />
                                        </div>
                                    </div>
                                    <div class="form-group row">                                        
                                        <div class="col-6">
                                            <label class="control-label mb-1">Estado:</label>
                                            <h:selectOneRadio id="genero" value="#{inventarioController.materialSeleccionado.estado}"
                                                              class="form-control">
                                                <f:selectItem itemValue="BUENO" itemLabel="Bueno&nbsp;&nbsp;"/>
                                                <f:selectItem itemValue="MALO" itemLabel="Malo&nbsp;&nbsp;"/>
                                            </h:selectOneRadio>
                                        </div>
                                        <div class="col-6">
                                            <label class="control-label mb-1">Disponibilidad:</label>
                                            <h:selectOneMenu id="estado" value="#{inventarioController.materialSeleccionado.disponilidad}"
                                                             class="form-control">
                                                <f:selectItem itemValue="" itemLabel="Seleccione si se encuentra disponible"/>
                                                <f:selectItems value="#{inventarioController.estadoMaterialList}" var="t" itemLabel="#{t.estado}"/>                                            
                                            </h:selectOneMenu>  
                                        </div>
                                    </div>
                                </h:form>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-danger letra-boton" data-dismiss="modal">Cerrar</button>
                                <h:commandLink actionListener="#{inventarioController.actualizar()}" class="btn btn-primary">Actualizar</h:commandLink> 
                            </div>
                        </div>
                    </h:panelGroup>
                </h:form>
            </div>
        </div>
        <!--modal editar-->

        <!--modal eliminar-->
        <div class="modal fade" id="modalEliminarMaterial" tabindex="-1" role="dialog" aria-labelledby="mediumModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
                <h:form prependId="false">
                    <h:panelGroup id="modalEliminarMaterialContent" class="modal-content" layout="block" >
                        <div class="modal-header">
                            <h5 class="modal-title" id="mediumModalLabel">Eliminar el material seleccionado</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>¿Está seguro de eliminar la solictiud #{inventarioController.materialSeleccionado.tipoMaterial} definitivamente del sistema?</p>                                                             
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                            <h:commandLink class="btn btn-danger" actionListener="#{inventarioController.eliminar()}">Si</h:commandLink>
                        </div>
                    </h:panelGroup>
                </h:form>
            </div>
        </div>
        <!--modal eliminar--> 

    </ui:define>

</ui:composition>